### ISSUE TITLE
Synology not accessible via domain when HTTP proxy (CDN) enabled.

### ISSUE THREAD

**Issue by bbbenji** [joshuaavalon/SynologyCloudflareDDNS#2]
Not sure if this is an issue with my DSM or CF. I am unable to access my DS when `DNS and HTTP proxy (CDN)` is enabled.

To prevent this script from turning this on I made the following modification:
`__PROXY__="false"`

**Comment by joshuaavalon** [comment]
If you cannot access when proxy is on, May be you should contact Cloudflare Support. Proxy is the feature of turning on or off the cloud icon next to the DNS record.

**Comment by joshuaavalon** [comment]
Most likely is there is something wrong with your DSM setting. You share the error here.

**Comment by bbbenji** [comment]
The issue occurred because I was using a port for HTTPS which was not supported by Cloudflare. For a full list of supported ports see: https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-Cloudflare-work-with-

**Comment by joshuaavalon** [comment]
You can setup reverse proxy to bypass that.

**Comment by captainhook** [comment]
@bbbenji not sure if this is relevant to you now 3 years later but I just this issue and corrected by turning off CF proxy

line 6, https://github.com/joshuaavalon/SynologyCloudflareDDNS/blob/master/cloudflareddns.sh#L6
change `proxy="true"` to `proxy="false"`

But probably better to setup reverse proxy with a CF compatible port.
