### ISSUE TITLE
badauth

### ISSUE THREAD

**Issue by KeshawnZhen** [joshuaavalon/SynologyCloudflareDDNS#20]
i run this script manually, return badauth.
whether this script can run in DMS7.0+ ?
Or the clouflare auth api has changed?

**Comment by joshuaavalon** [comment]
Did you use password instead of API token?

**Comment by KeshawnZhen** [comment]
> Did you use password instead of API token?

i tried api token and password both, but the result are same

**Comment by joshuaavalon** [comment]
Can you try to run the script manually with the following steps?

1. Replace the variables in

https://github.com/joshuaavalon/SynologyCloudflareDDNS/blob/d7d2e893177c7a94dc53a31a4924a671b70d43c4/cloudflareddns.sh#L9-L12

2. Add the following line in line 25.

```sh
echo "$res"
```

https://github.com/joshuaavalon/SynologyCloudflareDDNS/blob/d7d2e893177c7a94dc53a31a4924a671b70d43c4/cloudflareddns.sh#L23-L26

3. Run the script manually.

It should now print the response JSON to console. Can you share the response JSON? It should contain the reason why it is failing.

**Comment by KeshawnZhen** [comment]
the $res is: 
{"success":false,"errors":[{"code":7003,"message":"Could not route to \/zones\/**myLoginEmailString**\/dns_records, perhaps your object identifier is invalid?"},{"code":7000,"message":"No route for t
hat URI"}],"messages":[],"result":null}

I'm sure I can log in website normally by using this account

**Comment by joshuaavalon** [comment]
Please see https://github.com/joshuaavalon/SynologyCloudflareDDNS#setup-ddns

You need to enter `<Zone ID>` instead of username.
