### ISSUE TITLE
[Bug] Various synology web services constantly refreshing and never fully loading in browser

### ISSUE THREAD

**Issue by alexleonard** [joshuaavalon/SynologyCloudflareDDNS#21]
**Describe the bug**
So I'm a bit mystified by this. If I visit my NAS using its IP address everything loads and works fine. But if I use the DDNS sub-domain address I have set up (and which is pointing to the correct IP in Cloudflare thanks to this DDNS script), then I find that the page starts loading and then gets stuck in an eternal loop trying to load and restarting and trying to load and restarting. At first it seemed to only happen in Firefox, but then also happened in Chrome. I can't really work out what's causing the issue. As it doesn't happen when using the IP address, I wondered whether it could have something to do with this script and Cloudflare, or is it more likely a bug that I need to report to synology? I thought I'd check here first though.

Cheers!
Alex

**Comment by captainhook** [comment]
Most probably your Cloudflare TLS settings.

**Comment by joshuaavalon** [comment]
As @captainhook said, it most likely related to your TLS setting. You probably setup some kind of redirect to HTTPS. This script only update to IP to Cloudflare which does not cause this kind of problem.

If you do not know what is wrong, you should contact Cloudflare support.

**Comment by alexleonard** [comment]
Ok, thanks so much for letting me know and sorry for the noise in the git issue log! Much appreciate the point in the right direction. I'll investigate my settings!
