### ISSUE TITLE
[Bug] <Title>Can't get ipv6 address.

### ISSUE THREAD

**Issue by radiumliu** [joshuaavalon/SynologyCloudflareDDNS#22]
**Describe the bug**

It can't get the right ipv6 address.
would you fit it?

thanks !
<img width="716" alt="无标题" src="https://user-images.githubusercontent.com/65352113/160882568-414fc16b-6f34-430c-943d-d0e7135da2f3.png">
<img width="931" alt="无标题1" src="https://user-images.githubusercontent.com/65352113/160882588-c72420b3-c4c9-4f01-a027-da20f46cfe9b.png">

**Comment by joshuaavalon** [comment]
See #11 

You should ask Synology to fix it.
