### ISSUE TITLE
Is it possible to redirect multiple websites using Cloudflare?

### ISSUE THREAD

**Issue by datsnl** [joshuaavalon/SynologyCloudflareDDNS#23]
Thank you for creating this script.

I have used this script for one of my website to point to my synology
Is there a way to point multiple websites to different folders on my synology with Cloudflare using your script?

Kind regards

**Comment by joshuaavalon** [comment]
What you are looking for is reverse proxy. This script cannot help you with that.

There are many different reverse proxies. But what reverse proxies do is route the request to different application based the the request domain.
