### ISSUE TITLE
Cloudflare seems to stop working with this script

### ISSUE THREAD

**Issue by joshuaavalon** [joshuaavalon/SynologyCloudflareDDNS#3]
My DDNS has failed operation. Possible caused by the recid changed. 
This may need to update the README.md

**Comment by vkedwardli** [comment]
thanks for the repo, it's working fine to me.
Would be easier if the `__RECID__` and `__ZONE_ID__`  is inputted by the GUI (by csv style in the host field?)

**Comment by joshuaavalon** [comment]
@vkedwardli I would like to but Synology does not allow add number of fields to GUI. So there is no way to do that

**Comment by vkedwardli** [comment]
Although the hostname field doesn't support "," or "|" character, the Username/Email field do support that
