### ISSUE TITLE
Provider disappears

### ISSUE THREAD

**Issue by ZataH** [joshuaavalon/SynologyCloudflareDDNS#6]
After I add 1 ddns record, the provider disappears from the add new record. 
How do I fix that?

**Comment by joshuaavalon** [comment]
I don't understand what you mean. Can you provide a screenshot?

**Comment by IvoryAguado** [comment]
Basically when the __MYIP__ echo command is called does return an empty IP so when you update the record in CloudFlare will delete it

**Comment by joshuaavalon** [comment]
The new script will create or update the record.
