### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by hacky98** [joshuaavalon/SynologyCloudflareDDNS#7]
Hello,

how I get this script work with IPv6?
When I change "A" to "AAAA" in the config file, it don't works.
After finishing the configuration the window looks like this when I open it again. It don't shows my IPv6 address. During the first configuration it shows my IPv6 address.

<img width="765" alt="Bildschirmfoto 2019-04-19 um 01 39 57" src="https://user-images.githubusercontent.com/1338837/56397488-3c458d00-6244-11e9-9748-07aa1aa78788.png">

**Comment by Kovah** [comment]
I quickly checked this and it seems that the DSM does not pass the IPv6 address to the script.

**Comment by joshuaavalon** [comment]
The address is provided by Synology.
