### ISSUE TITLE
[Bug] A small problem in commonds for Synology

### ISSUE THREAD

**Issue by bootcamp6** [joshuaavalon/SynologyCloudflareDDNS#8]
**Describe the bug**
In the commond of download cloudflareddns.sh
wget https://raw.githubusercontent.com/joshuaavalon/SynologyCloudflareDDNS/master/cloudflareddns.sh -O /sbin/cloudflaredns.sh

The file has been renamed as cloudflaredns.sh (not cloudflareddns.sh)

Then if the user just copy the code in step 3:
cat >> /etc.defaults/ddns_provider.conf << 'EOF'
[Cloudflare]
        modulepath=/sbin/cloudflareddns.sh

In this case, the Synology DDNS setting cannot find correct file to run the commonds.

**Comment by joshuaavalon** [comment]
Close by d7d2e893177c7a94dc53a31a4924a671b70d43c4
